---

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml

- include: setup_repo.yml

- include: setup_requirements.yml

- include: setup_supervisor.yml

- include: set_file_permissions.yml

- include: setup_nginx.yml
